import { Dinner, FoodWithQuantity } from '../@types';

export const FrenchDinner: Dinner = {
  dinnerId: 1,
  dinnerOrderable: true,
  dinnerQuantity: 1,
  dinnerFoodInfoResponseList: [{ foodId: 1, foodName: '', foodQuantity: 1 }],
  dinnerName: '프렌치 디너 세트',
  dinnerImage: '/Dinner.png',
  dinnerDescription:
    '프렌치 디너는 커피 한잔, 와인 한잔, 샐러드, 스테이크가 제공되며 미스터 대박 디너 서비스의 인기 세트 중 하나로 프랑스식의 근사한 저녁 식사를 드실 수 있습니다',
  excludedStyleInfoResponseList: [
    { excludedStyleName: 'simple', excludedStyleId: 0 },
    { excludedStyleName: 'grande', excludedStyleId: 0 },
    { excludedStyleName: 'deluxe', excludedStyleId: 0 },
  ],
};

export const Foods: FoodWithQuantity[] = [
  {
    foodId: 1,
    foodOrderable: true,
    foodName: '감자',
    foodSellPrice: 500,
    foodCategory: 'meat',
    foodQuantity: 0,
  },
  {
    foodId: 2,
    foodOrderable: true,
    foodName: '고구마',
    foodSellPrice: 1000,
    foodCategory: 'meat',
    foodQuantity: 0,
  },
  {
    foodId: 3,
    foodOrderable: true,
    foodName: '스테이크',
    foodSellPrice: 5000,
    foodCategory: 'meat',
    foodQuantity: 0,
  },
  {
    foodId: 4,
    foodOrderable: true,
    foodName: '브레드',
    foodSellPrice: 1500,
    foodCategory: 'meat',
    foodQuantity: 0,
  },
  {
    foodId: 5,
    foodOrderable: true,
    foodName: '커피',
    foodSellPrice: 500,
    foodCategory: 'meat',
    foodQuantity: 0,
  },
  {
    foodId: 6,
    foodOrderable: true,
    foodName: '감자2',
    foodSellPrice: 500,
    foodCategory: 'rice',
    foodQuantity: 0,
  },
  {
    foodId: 7,
    foodOrderable: true,
    foodName: '고구마2',
    foodSellPrice: 1000,
    foodCategory: 'rice',
    foodQuantity: 0,
  },
  {
    foodId: 8,
    foodOrderable: true,
    foodName: '스테이크2',
    foodSellPrice: 5000,
    foodCategory: 'rice',
    foodQuantity: 0,
  },
  {
    foodId: 9,
    foodOrderable: true,
    foodName: '브레드2',
    foodSellPrice: 1500,
    foodCategory: 'rice',
    foodQuantity: 0,
  },
  {
    foodId: 10,
    foodOrderable: true,
    foodName: '커피2',
    foodSellPrice: 500,
    foodCategory: 'rice',
    foodQuantity: 0,
  },
  {
    foodId: 11,
    foodOrderable: true,
    foodName: '감자3',
    foodSellPrice: 500,
    foodCategory: 'drink',
    foodQuantity: 0,
  },
  {
    foodId: 12,
    foodOrderable: true,
    foodName: '고구마3',
    foodSellPrice: 1000,
    foodCategory: 'drink',
    foodQuantity: 0,
  },
  {
    foodId: 13,
    foodOrderable: true,
    foodName: '스테이크3',
    foodSellPrice: 5000,
    foodCategory: 'drink',
    foodQuantity: 0,
  },
  {
    foodId: 14,
    foodOrderable: true,
    foodName: '브레드3',
    foodSellPrice: 1500,
    foodCategory: 'drink',
    foodQuantity: 0,
  },
  {
    foodId: 15,
    foodOrderable: true,
    foodName: '커피3',
    foodSellPrice: 500,
    foodCategory: 'drink',
    foodQuantity: 0,
  },
];

export type FoodKeyType = typeof Foods;
